spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/studentdb
spring.datasource.username=postgres
spring.datasource.password=Preetichoudhary.ad@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
